#lib.loc <- "/scratch/user/hcchung/R_LIBS_USER/4.0.3-foss-2020a-recommended-mt/"
#install.packages("ape",lib= lib.loc, dependencies=TRUE)
#install.packages("phytools",lib= lib.loc, dependencies=TRUE)
#install.packages("phylobase",lib=lib.loc, dependencies=TRUE)
#install.packages("text2vec",lib=lib.loc, dependencies=TRUE)
#install.packages("ppcor",lib=lib.loc, dependencies=TRUE)
#install.packages("huge",lib=lib.loc, dependencies=TRUE)
#install.packages("igraph",lib=lib.loc, dependencies=TRUE)
#install.packages("BDgraph",lib=lib.loc, dependencies=TRUE)
#install.packages("gridExtra",lib=lib.loc, dependencies=TRUE)
#library(devtools)
#install_github("zdk123/SpiecEasi",lib= "/scratch/user/hcchung/R_LIBS_USER/4.0.3-foss-2020a-recommended-mt/", dependencies=TRUE)
#install.packages("truncdist",lib=lib.loc, dependencies=TRUE)
#install.packages("truncnorm",lib=lib.loc, dependencies=TRUE)
#install.packages("tmvtnorm",lib=lib.loc, dependencies=TRUE)
#install.packages("mvtnorm",lib=lib.loc, dependencies=TRUE)
#if (!requireNamespace("BiocManager", quietly = TRUE))
#    install.packages("BiocManager")
#BiocManager::install("phyloseq",lib=lib.loc, dependencies=TRUE)
library(ape)
library(phytools)
library(phylobase)
library(phyloseq)
library(text2vec)
library(ppcor)
library(boot)
library(Matrix)
library(truncnorm); #Univariate truncated normal
library(huge);
library(igraph)
library(BDgraph)
library(plyr);
library(ggplot2);
library(reshape);
library(gridExtra)
library(doParallel)
library(SPRING)
library(SpiecEasi)
library(tmvtnorm)
library(mvtnorm)
library(truncdist)


#lib.loc = "/scratch/user/hcchung/Rpackages/"
#.libPaths("/scratch/user/hcchung/Rpackages/")

#install.packages("doParallel", lib= lib.loc, dependencies=TRUE)
#install.packages("reshape", lib= lib.loc, dependencies=TRUE)
#install.packages("reshape", lib= lib.loc, dependencies=TRUE)
#install.packages("matrixcalc", lib= lib.loc, dependencies=TRUE)
#install.packages("phytools", lib= lib.loc, dependencies=TRUE)
#install.packages("ape",lib= lib.loc, dependencies=TRUE)
#install.packages("phytools",lib= lib.loc, dependencies=TRUE)
#install.packages("phylobase",lib=lib.loc, dependencies=TRUE)
#install.packages("text2vec",lib=lib.loc, dependencies=TRUE)
#install.packages("ppcor",lib=lib.loc, dependencies=TRUE)
#install.packages("huge",lib=lib.loc, dependencies=TRUE)
#install.packages("igraph",lib=lib.loc, dependencies=TRUE)
#install.packages("BDgraph",lib=lib.loc, dependencies=TRUE)
#install.packages("gridExtra",lib=lib.loc, dependencies=TRUE)
#library(devtools);install.packages("devtools",lib=lib.loc, dependencies=TRUE)
#install_github("zdk123/SpiecEasi",lib=lib.loc, dependencies=TRUE)
#install.packages("truncdist",lib=lib.loc, dependencies=TRUE)
#install.packages("truncnorm",lib=lib.loc, dependencies=TRUE)
#install.packages("tmvtnorm",lib=lib.loc, dependencies=TRUE)
#install.packages("mvtnorm",lib=lib.loc, dependencies=TRUE)
#install.packages("Rcpp",lib=lib.loc, dependencies=TRUE)
#install.packages("RcppArmadillo",lib=lib.loc, dependencies=TRUE)
#install.packages("boot",lib=lib.loc, dependencies=TRUE)
#if (!requireNamespace("BiocManager", quietly = TRUE))
#    install.packages("BiocManager")
#BiocManager::install("phyloseq",lib=lib.loc, dependencies=TRUE)
